-- ============================================================
-- Wave 1.3 — RLS hotfix for users SELECT
-- ============================================================
-- 2026-05-24
--
-- Problem:
--   The W1.1 policy `users_self_or_admin_select` blocks Google OAuth
--   managers from reading their own user row. Their auth.users.id
--   (generated by Supabase Auth from the Google OAuth flow) does not
--   match public.users.id (set by admin much earlier, different UUID).
--   Result: SELECT against /rest/v1/users returns 500 / empty,
--   manager login fails post-OAuth.
--
-- Fix:
--   Drop the strict policy. Replace with one that allows any
--   AUTHENTICATED caller to SELECT users (matches pre-Wave-1
--   behavior) but keeps anonymous (no JWT) callers blocked — the
--   original P0 concern was anon dumping the table via the public
--   anon key. That closure remains in place.
--
--   Write policies (INSERT/UPDATE/DELETE) stay strict — only
--   admins can mutate. Hierarchy on stores/visits/farms unchanged.
--
-- Idempotent: DROP IF EXISTS + CREATE.
-- ============================================================

DROP POLICY IF EXISTS users_self_or_admin_select ON public.users;
DROP POLICY IF EXISTS users_authenticated_select ON public.users;

CREATE POLICY users_authenticated_select ON public.users
  FOR SELECT
  TO authenticated
  USING (true);

-- Comment on the policy so the intent survives in the schema dump.
COMMENT ON POLICY users_authenticated_select ON public.users IS
  'W1.3 hotfix 2026-05-24: any authenticated user can read users; anon blocked. Write/delete stay strict. The original W1.1 self-or-admin scope is restored on a per-query basis in app code where it matters.';
